CREATE TABLE IF NOT EXISTS AUCTIONS
(
    ID int NOT NULL PRIMARY KEY,
    ITEM_NAME varchar(255) NOT NULL,
    ITEM_DESCRIPTION varchar(255) NOT NULL,
    INITIAL_VALUE numeric(10,2) NOT NULL,
    STATUS varchar(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS BID
(
    ID int NOT NULL PRIMARY KEY,
    AUCTION_ID int NOT NULL,
    AMOUNT numeric(10,2) NOT NULL,
    STATUS varchar(45) NOT NULL
);
