DROP TABLE IF EXISTS AUCTIONS;
DROP TABLE IF EXISTS BIDS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE AUCTIONS
(
    ID SERIAL PRIMARY KEY,
    ITEM_NAME varchar(255) NOT NULL,
    TITLE varchar(255) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    INITIAL_VALUE numeric(10,2) NOT NULL,
    EXPIRATION_DATE timestamp NOT NULL,
    IMAGE_URL varchar(255),
    STATUS varchar(45) NOT NULL,
    USER_ID INT NOT NULL
);

CREATE TABLE BIDS
(
    ID SERIAL PRIMARY KEY,
    AUCTION_ID int NOT NULL,
    AMOUNT numeric(10,2) NOT NULL,
    STATUS varchar(45) NOT NULL DEFAULT 'INSERTED',
    USER_ID int NOT NULL
);

CREATE TABLE USERS
(
    ID SERIAL PRIMARY KEY,
    USER_NAME varchar(45) NOT NULL,
    PUBLIC_KEY varchar(58) NOT NULL
);

