SET MODE PostgreSQL;
insert into AUCTIONS (ID, ITEM_NAME, ITEM_DESCRIPTION, INITIAL_VALUE, STATUS) VALUES (1,'AN_ITEM_NAME','AN_ITEM_DESCRIPTION',10.99,'SOLD');
insert into BID (ID, AUCTION_ID, AMOUNT, STATUS, USER_ID) VALUES (1,1,20.99, 'ACCEPTED', 'AN_USER_ID');