spring:
  main:
    lazy-initialization: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    schema: classpath:sql/schema.sql
    data: classpath:sql/test-data.sql
  h2:
    console:
      enabled: true
  config:
    import: classpath:algorand.properties