spring:
  datasource:
    driverClassName: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  application:
    name: algorand-auction
  server:
    error:
      whitelabel:
        enabled: false