SET MODE PostgreSQL;

CREATE TABLE IF NOT EXISTS AUCTIONS
(
    ID int NOT NULL PRIMARY KEY,
    NAME varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ID int NOT NULL PRIMARY KEY,
    AUCTION_ID int NOT NULL,
    `NAME` varchar(255) NOT NULL,
    STATUS varchar(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS BID
(
    ID int NOT NULL PRIMARY KEY,
    AUCTION_ID int NOT NULL,
    AMOUNT money NOT NULL,
    STATUS varchar(45) NOT NULL
);


insert into AUCTIONS (ID, NAME) VALUES (1,'AN_AUCTION');
insert into ITEMS (ID, AUCTION_ID, NAME, STATUS) VALUES (1,1,'AN_AUCTION', 'SOLD');
insert into BID (ID, AUCTION_ID, AMOUNT, STATUS) VALUES (1,1,'10', 'ACCEPTED');